export const agenciesList = [
  {
    AgencyName: "Department of Health",
    AgencyInitial: "DH",
    Status: "Active",
    ContactNumber: "+6328651-7800",
    Email: "info@doh.gov.ph",
    isActive: true,
  },
  {
    AgencyName: "Philippine National Police",
    AgencyInitial: "PN",
    Status: "Active",
    ContactNumber: "+6328722-0650",
    Email: "pnpdpcr@gmail.com",
    isActive: true,
  },
  {
    AgencyName: "Department of Education",
    AgencyInitial: "DE",
    Status: "Active",
    ContactNumber: "+6328633-7248",
    Email: "action@deped.gov.ph",
    isActive: true,
  },
  {
    AgencyName: "Department of Transportation",
    AgencyInitial: "DT",
    Status: "Active",
    ContactNumber: "+6327908-8800",
    Email: "dotr2020@gmail.com",
    isActive: true,
  },
  {
    AgencyName: "Department of Tourism",
    AgencyInitial: "DT",
    Status: "Active",
    ContactNumber: "+6328652-5252",
    Email: "info@tourism.gov.ph",
    isActive: true,
  },
  {
    AgencyName: "Department of Trade and Industry",
    AgencyInitial: "DT",
    Status: "Active",
    ContactNumber: "+6327751-0384",
    Email: "consumercare@dti.gov.ph",
    isActive: true,
  },
  {
    AgencyName: "Department of Finance",
    AgencyInitial: "DF",
    Status: "Active",
    ContactNumber: "+6328524-0335",
    Email: "contactus@dof.gov.ph",
    isActive: true,
  },
  {
    AgencyName: "Philippine Institute of Volcanology and Seismology",
    AgencyInitial: "PI",
    Status: "Active",
    ContactNumber: "+6328926-2611",
    Email: "mail@phivolcs.dost.gov.ph",
    isActive: true,
  },
  {
    AgencyName: "Philippine Coast Guard",
    AgencyInitial: "PC",
    Status: "Active",
    ContactNumber: "+6328527-8481",
    Email: "cgadm@coastguard.gov.ph",
    isActive: true,
  },
  {
    AgencyName: "Commission on Elections",
    AgencyInitial: "CE",
    Status: "Active",
    ContactNumber: "+6328525-9296",
    Email: "info@comelec.gov.ph",
    isActive: true,
  },
]
